/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Viewer;

import DOMAIN.Aluno;
import DOMAIN.Personal;
import GERENCIADOR.FuncaoAjuda;
import GERENCIADOR.GerenciadorIG;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class TelaCadastroAluno extends javax.swing.JDialog {

    private Aluno alunoSelect = null;  
   
    public TelaCadastroAluno(java.awt.Frame parent, boolean modal, GerenciadorIG newGerenIG) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        buttonGroupTreino = new javax.swing.ButtonGroup();
        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelDataNas = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        cpfFormated = new javax.swing.JFormattedTextField();
        labelBairro = new javax.swing.JLabel();
        txtDiaVencimento = new javax.swing.JTextField();
        labelRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        telefoneForm = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        buttonFoto = new javax.swing.JButton();
        panelSexo = new javax.swing.JPanel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFeminino = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonTreinoS = new javax.swing.JRadioButton();
        jRadioButtonTreinoN = new javax.swing.JRadioButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        labelCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        labelCEP = new javax.swing.JLabel();
        cepFormated = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboTipoPlano = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();
        dataCadastro = new javax.swing.JLabel();
        dateCadastro = new com.toedter.calendar.JDateChooser();
        dataVencimento = new javax.swing.JLabel();
        txtBairro1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboPersonal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        labelNome.setText("Nome:");

        labelDataNas.setText("Data Nascimento:");

        labelCPF.setText("CPF: ");

        try {
            cpfFormated.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelBairro.setText("Bairro:");

        labelRua.setText("Rua:");

        labelEmail.setText("E-mail:");

        labelTelefone.setText("Telefone: ");

        try {
            telefoneForm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        labelFoto.setText("              Foto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        );

        buttonFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-pesquisar-12.png"))); // NOI18N
        buttonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFotoActionPerformed(evt);
            }
        });

        panelSexo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        buttonGroupSexo.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setMnemonic('M');
        jRadioButtonMasculino.setText("Masculino");

        buttonGroupSexo.add(jRadioButtonFeminino);
        jRadioButtonFeminino.setMnemonic('F');
        jRadioButtonFeminino.setText("Feminino");

        javax.swing.GroupLayout panelSexoLayout = new javax.swing.GroupLayout(panelSexo);
        panelSexo.setLayout(panelSexoLayout);
        panelSexoLayout.setHorizontalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSexoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jRadioButtonMasculino))
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addComponent(jRadioButtonFeminino)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSexoLayout.setVerticalGroup(
            panelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonFeminino)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Já treinou?"));

        buttonGroupTreino.add(jRadioButtonTreinoS);
        jRadioButtonTreinoS.setMnemonic('S');
        jRadioButtonTreinoS.setText("Sim");

        buttonGroupTreino.add(jRadioButtonTreinoN);
        jRadioButtonTreinoN.setMnemonic('N');
        jRadioButtonTreinoN.setText("Não");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonTreinoN)
                    .addComponent(jRadioButtonTreinoS))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonTreinoS)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonTreinoN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-ok-16.png"))); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-cancelar-16.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-vassoura-16.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        labelCidade.setText("Cidade:");

        labelCEP.setText("CEP: ");

        try {
            cepFormated.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Cadastro de Alunos");

        jLabel13.setText("Tipo do Plano:");

        comboTipoPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensalidade", "Trimestral", "Anual" }));

        dataCadastro.setText("Data do Cadastro:");

        dataVencimento.setText("Dia de Vencimento:");

        jLabel1.setText("Personal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dataCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTelefone)
                        .addGap(5, 5, 5)
                        .addComponent(telefoneForm, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCidade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCEP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cepFormated, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(buttonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboTipoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dataVencimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(72, 72, 72)
                                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelCPF)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cpfFormated, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelDataNas)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDataNas)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCPF)
                            .addComponent(cpfFormated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCEP)
                            .addComponent(cepFormated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(9, 9, 9)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataCadastro))
                    .addComponent(dateCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRua)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataVencimento)
                    .addComponent(txtDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(telefoneForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(comboTipoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonLimpar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFotoActionPerformed
        colocarFoto();
    }//GEN-LAST:event_buttonFotoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparEscolha();
        // limpar as seções dos dados que foram preenchidos
        setarCoresErro();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jButtonCancelar.addActionListener(e -> dispose());
        // ao clicar no botão cancelar fecha a tela, não se essa será uma maneira correta de se fazer isso, pedi ajuda para o chatGPT
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // Apos integração com o banco de dados fazer o cadastro do aluno no banco de dados 
        
        String nome = txtNome.getText();
        Date dataNascimento = date.getDate();
        String cpf = cpfFormated.getText();
        String cep = cepFormated.getText();
        String cidade = txtCidade.getText();
        String bairro = txtBairro1.getText();
        String rua = txtRua.getText();
        String email = txtEmail.getText();
        String telefone = telefoneForm.getText();
        Icon foto = labelFoto.getIcon();
        char sexo = (char) buttonGroupSexo.getSelection().getMnemonic();
        boolean jaTreinou;
        if(buttonGroupTreino.getSelection().getMnemonic() == 'S'){
            jaTreinou = true;
        }else{
            jaTreinou = false;
        }
        String tipoPlano = (String) comboTipoPlano.getSelectedItem();
        Date dataCadastro = dateCadastro.getDate();
        int diaVencimento = Integer.parseInt(txtDiaVencimento.getText());
        Personal personal = (Personal) comboPersonal.getSelectedItem();
        
        if(validarCampos()){  
            
            if(alunoSelect == null){
                alunoSelect = GerenciadorIG.getMyInstance().getGerDom().inserirAluno(nome, dataNascimento, cpf, cep, cidade, bairro, rua, 
                        email, telefone, foto, sexo, jaTreinou, tipoPlano, diaVencimento, dataCadastro, personal);
                
                JOptionPane.showMessageDialog(this, "Aluno " + alunoSelect.getIdAluno() + " inserido com sucesso.", "Cadastro de Aluno", JOptionPane.INFORMATION_MESSAGE); 
            }else{
                GerenciadorIG.getMyInstance().getGerDom().alterarAluno(alunoSelect, nome, dataNascimento, cpf, cep, cidade, bairro, rua, 
                        email, telefone, foto, sexo, jaTreinou, tipoPlano, diaVencimento);
                JOptionPane.showMessageDialog(this, "Aluno " + alunoSelect.getIdAluno() + " inserido com sucesso.", "Cadastro de Aluno", JOptionPane.INFORMATION_MESSAGE); 
            }
            
            limparEscolha();
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        List<Personal> listaPersonal = GerenciadorIG.getMyInstance().getGerDom().listarPersonal(Personal.class);
        if(listaPersonal.isEmpty()){
            JOptionPane.showMessageDialog(this, "Adicione algum personal primeiro", "Cadastro de aluno", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }else{
            FuncaoAjuda.carregarCombo(comboPersonal, listaPersonal);
        }
        
    }//GEN-LAST:event_formComponentShown

    private boolean validarCampos(){
        String mensgErro = "";
        String numberCEP = cepFormated.getText().replaceAll("[ .()/ -]", "");
        String numberTelefone = telefoneForm.getText().replaceAll("[ .()/ -]", "");
        
        if(txtNome.getText().isEmpty()){
            mensgErro = mensgErro + "Digite um nome válido\n";
            labelNome.setForeground(Color.red);
        }
        
         if(date ==  null){
            mensgErro = mensgErro + "Digite uma data de nascimento válido\n";
            labelDataNas.setForeground(Color.red);
        }
        
        if(FuncaoAjuda.isCPF(cpfFormated.getText()) == false){
            mensgErro = mensgErro + "Digite um CPF válido\n";
            labelCPF.setForeground(Color.red);
        }
        
        if(numberCEP.isEmpty()){
            mensgErro = mensgErro + "Digite um CEP válido\n";
            labelCEP.setForeground(Color.red);
        }
        
        if(txtCidade.getText().isEmpty()){
            mensgErro = mensgErro + "Digite um nome de uma cidade válido\n";
            labelCidade.setForeground(Color.red);
        }
        
        if(txtDiaVencimento.getText().isEmpty()){
            mensgErro = mensgErro + "Digite um nome de um bairro válido\n";
            labelBairro.setForeground(Color.red);
        }
        
        if(txtRua.getText().isEmpty()){
            mensgErro = mensgErro + "Digite um nome de uma rua válida\n";
            labelRua.setForeground(Color.red);
        }
        
        if(txtEmail.getText().isEmpty()){
            mensgErro = mensgErro + "Digite um e-mail válido\n";
            labelEmail.setForeground(Color.red);
        }
        
        if(numberTelefone.isEmpty()){
            mensgErro = mensgErro + "Digite um telefone válido\n";
            labelTelefone.setForeground(Color.red);
        }
                
        if(buttonGroupSexo.getSelection() == null){
            mensgErro = mensgErro + "Marque uma opção de sexo válida\n";
        }
        
        if(buttonGroupTreino.getSelection() == null){
            mensgErro = mensgErro + "Marque uma opção de treino válida\n";
        }
        
        if(dataCadastro == null){
            mensgErro = mensgErro + "Digite uma data de cadastro válida\n";
            labelDataNas.setForeground(Color.red);
        }
        
        if(txtDiaVencimento.getText().isEmpty()){
            mensgErro = mensgErro + "Digite uma data válida\n";
            dataVencimento.setForeground(Color.red);    
        }
        
        if(mensgErro.isEmpty()){
            setarCoresErro();
            return true;
        }else{
            JOptionPane.showMessageDialog(this, mensgErro, "Cadastro de aluno", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
    }
    
    private void setarCoresErro(){
        labelNome.setForeground(Color.black);
        labelTelefone.setForeground(Color.black);
        labelEmail.setForeground(Color.black);
        labelRua.setForeground(Color.black);
        labelBairro.setForeground(Color.black);
        labelCidade.setForeground(Color.black);
        labelCEP.setForeground(Color.black);
        labelCPF.setForeground(Color.black);
        labelDataNas.setForeground(Color.black);
        dataCadastro.setForeground(Color.black);
        dataVencimento.setForeground(Color.black);
    }
    
    private void limparEscolha(){
        txtNome.setText("");
        txtDiaVencimento.setText("");
        txtEmail.setText("");
        txtRua.setText("");
        date.setDate(null);
        cpfFormated.setText("");
        telefoneForm.setText("");
        labelFoto.setIcon(null);
        labelFoto.setText("              Foto");
        buttonGroupSexo.clearSelection();
        buttonGroupTreino.clearSelection();
        txtCidade.setText("");
        dateCadastro.setDate(null);
        txtDiaVencimento.setText("");
        txtBairro1.setText("");
        cepFormated.setText("");
    }
    
    private void colocarFoto(){//COLOCAR IMAGEM
        JFileChooser janArq = new JFileChooser();
        
        janArq.setAcceptAllFileFilterUsed(false);
        janArq.setFileFilter(new FileNameExtensionFilter("Arquivos de imagem", "png", "jpg", "gif "));
        
        if(janArq.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File arq = janArq.getSelectedFile();
            ImageIcon imagem = new ImageIcon(arq.getAbsolutePath());
            mostrarFoto(imagem); 
        }
        
        // colocar a foto no label
    }
    
    private void mostrarFoto(ImageIcon foto){
        foto.setImage(foto.getImage().getScaledInstance(labelFoto.getWidth(), labelFoto.getHeight(), Image.SCALE_DEFAULT));
        labelFoto.setText("");
        labelFoto.setIcon(foto);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFoto;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.ButtonGroup buttonGroupTreino;
    private javax.swing.JFormattedTextField cepFormated;
    private javax.swing.JComboBox<String> comboPersonal;
    private javax.swing.JComboBox<String> comboTipoPlano;
    private javax.swing.JFormattedTextField cpfFormated;
    private javax.swing.JLabel dataCadastro;
    private javax.swing.JLabel dataVencimento;
    private com.toedter.calendar.JDateChooser date;
    private com.toedter.calendar.JDateChooser dateCadastro;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonFeminino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JRadioButton jRadioButtonTreinoN;
    private javax.swing.JRadioButton jRadioButtonTreinoS;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelDataNas;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JPanel panelSexo;
    private javax.swing.JFormattedTextField telefoneForm;
    private javax.swing.JTextField txtBairro1;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtDiaVencimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
