/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Viewer;

import DOMAIN.Aluno;
import DOMAIN.Exercicios;
import DOMAIN.FichaAluno;
import GERENCIADOR.FuncaoAjuda;
import GERENCIADOR.GerenciadorIG;
import GERENCIADOR.GerenciadorDominio;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;

/**
 *
 * @author User
 */
public class TelaCadastroFicha extends javax.swing.JDialog {

    private GerenciadorIG genIG;
    private Map<Exercicios, JCheckBox> checkBoxListaExercicios = new HashMap<>();;
    private List <Exercicios> exerciciosSelecionados = new ArrayList<>();
    private FichaAluno fichaSelect = null;
    private Aluno alunoSelect = null;
    private List<Exercicios> listaExercicios = new ArrayList<>();
    
    public TelaCadastroFicha(java.awt.Frame parent, boolean modal, GerenciadorIG newGerenIG) {
        super(parent, modal);
        this.genIG = newGerenIG;
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboTipoFicha = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        agachamento = new javax.swing.JCheckBox();
        sulpinoHalter = new javax.swing.JCheckBox();
        desenvolvimento = new javax.swing.JCheckBox();
        remadabaixa = new javax.swing.JCheckBox();
        afundo = new javax.swing.JCheckBox();
        prancha = new javax.swing.JCheckBox();
        sulpinoReto = new javax.swing.JCheckBox();
        legPress = new javax.swing.JCheckBox();
        roscaDireta = new javax.swing.JCheckBox();
        crucifixo = new javax.swing.JCheckBox();
        barraFixa = new javax.swing.JCheckBox();
        tricepsCorda = new javax.swing.JCheckBox();
        terraLevantar = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        spinnerQTDserie = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spinnerMinRep = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinnerMaxRep = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        comboDescanso = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaObs = new javax.swing.JTextArea();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        comboNomes = new javax.swing.JComboBox<>();
        labelNasci = new javax.swing.JLabel();
        labelAltura = new javax.swing.JLabel();
        txtGorduraCorp = new javax.swing.JTextField();
        labelPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        buttonBuscarAluno = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtAltura1 = new javax.swing.JTextField();
        labelGordura = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        labelIdade = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        nasciData = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Fichas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel1.setAutoscrolls(true);

        jLabel1.setText("Objetivo:");

        comboTipoFicha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emagrecimento", "Hipertrofia", "Força/Potência", " " }));
        comboTipoFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoFichaActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Exercícios"));

        agachamento.setText("Agachamento Livre ");

        sulpinoHalter.setText("Sulpino Reto com Halteres");

        desenvolvimento.setText("Desenvolvimento Ombro");

        remadabaixa.setText("Remada Baixa");

        afundo.setText("Afundo Alternado");

        prancha.setText("Prancha Abdominal");

        sulpinoReto.setText("Sulpino Reto Barra");

        legPress.setText("Leg Press 45°");

        roscaDireta.setText("Rosca Direta");

        crucifixo.setText("Crucifixo Máquina");

        barraFixa.setText("Barra Fixa");

        tricepsCorda.setText("Tríceps Corda");

        terraLevantar.setText("Levantamento Terra");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sulpinoHalter)
                    .addComponent(agachamento)
                    .addComponent(remadabaixa)
                    .addComponent(afundo)
                    .addComponent(prancha)
                    .addComponent(desenvolvimento))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tricepsCorda)
                    .addComponent(roscaDireta)
                    .addComponent(sulpinoReto)
                    .addComponent(crucifixo)
                    .addComponent(terraLevantar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(legPress)
                        .addGap(101, 101, 101)
                        .addComponent(barraFixa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agachamento)
                    .addComponent(legPress)
                    .addComponent(barraFixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sulpinoHalter)
                    .addComponent(sulpinoReto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remadabaixa)
                    .addComponent(crucifixo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afundo)
                    .addComponent(roscaDireta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desenvolvimento)
                    .addComponent(tricepsCorda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prancha)
                    .addComponent(terraLevantar))
                .addGap(17, 17, 17))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade Séries"));

        spinnerQTDserie.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(spinnerQTDserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(spinnerQTDserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade Repetições"));
        jPanel4.setAutoscrolls(true);

        jLabel2.setText("Min:");

        spinnerMinRep.setModel(new javax.swing.SpinnerNumberModel(4, 4, 12, 1));

        jLabel3.setText("Máx:");

        spinnerMaxRep.setModel(new javax.swing.SpinnerNumberModel(6, 6, 15, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerMinRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinnerMaxRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerMinRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerMaxRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo Descanso"));

        comboDescanso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "60", "120" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(comboDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(comboDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));

        textAreaObs.setColumns(20);
        textAreaObs.setRows(5);
        jScrollPane1.setViewportView(textAreaObs);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-ok-16.png"))); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-cancelar-16.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        labelNome.setText("Nome: ");

        comboNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNomesActionPerformed(evt);
            }
        });

        labelNasci.setText("Data Nascimento");

        labelAltura.setText("Altura: ");

        labelPeso.setText("Peso: ");

        buttonBuscarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-pesquisar-12.png"))); // NOI18N
        buttonBuscarAluno.setText("Buscar Aluno");
        buttonBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarAlunoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-vassoura-16.png"))); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelGordura.setText("Porcentagem de Gordura Corporal:");

        labelIdade.setText("Idade:");

        jLabel10.setText("Nome da pesquisa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(labelAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelGordura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGorduraCorp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNasci)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nasciData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(labelIdade)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)
                                .addComponent(comboTipoFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addComponent(buttonBuscarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNome)
                        .addComponent(comboNomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBuscarAluno)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNasci)
                    .addComponent(nasciData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelIdade)
                        .addComponent(jLabel1)
                        .addComponent(comboTipoFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPeso)
                    .addComponent(labelAltura)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGordura)
                    .addComponent(txtGorduraCorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jButtonCancelar.addActionListener(e -> dispose());
        // ao clicar no botão cancelar fecha a tela, não se essa será uma maneira correta de se fazer isso, pedi ajuda para o chatGPT
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void comboTipoFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoFichaActionPerformed
        String tipoFicha = comboTipoFicha.getSelectedItem().toString();   
        FichaAluno ficha = GerenciadorDominio.fichaPredefinida(tipoFicha, listaExercicios);
        setarFicha(ficha);
    }//GEN-LAST:event_comboTipoFichaActionPerformed

    private void buttonBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarAlunoActionPerformed
        String pesq = txtBusca.getText();
        List<Aluno> listaAluno = GerenciadorIG.getMyInstance().getGerDom().pesquisarNomeAluno(pesq, Aluno.class);
        FuncaoAjuda.carregarCombo(comboNomes, listaAluno);
    }//GEN-LAST:event_buttonBuscarAlunoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       limparEscolhas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        Aluno alu = (Aluno) comboNomes.getSelectedItem();

        String objetivo = (String) comboTipoFicha.getSelectedItem();
        double peso = Double.parseDouble(txtPeso.getText());
        double altura = Double.parseDouble(txtAltura1.getText());
        double porcentoGordura = Double.parseDouble(txtGorduraCorp.getText());

        exerciciosSelecionados.clear(); // limpa a lista sempre que o botão for apertado

        for (Map.Entry<Exercicios, JCheckBox> entry : checkBoxListaExercicios.entrySet()) {
            JCheckBox checkBox = entry.getValue();

            if (checkBox.isSelected()) {
                Exercicios exercicio = entry.getKey();
                exerciciosSelecionados.add(exercicio);
            }
        }
        String obs = textAreaObs.getText();
        int quantSerie = (Integer) spinnerQTDserie.getValue();
        int minRep = (Integer) spinnerMinRep.getValue();
        int maxRep = (Integer) spinnerMaxRep.getValue();
        int tempDescando = Integer.parseInt((String) comboDescanso.getSelectedItem());

        if (validarCampos()) {

            fichaSelect = GerenciadorIG.getMyInstance().getGerDom().inserirFicha(alu, objetivo, exerciciosSelecionados, porcentoGordura, peso, altura, minRep,
                    maxRep, tempDescando, quantSerie, new Date(), obs);
            JOptionPane.showMessageDialog(this, "Ficha de treino " + fichaSelect.getIdFicha() + " inserido com sucesso.", "Cadastro de Ficha", JOptionPane.INFORMATION_MESSAGE);

            limparEscolhas();
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void comboNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNomesActionPerformed
        Aluno alu = (Aluno) comboNomes.getSelectedItem();
        if(alu != null){
            Date nasci = alu.getDataNasc();
            nasciData.setDate(nasci);
        }
    }//GEN-LAST:event_comboNomesActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        listaExercicios = GerenciadorIG.getMyInstance().getGerDom().listarExercicios(Exercicios.class);
        
        if (listaExercicios.isEmpty()) {
            String[] nomesExercicios = {
                "Agachamento Livre",
                "Sulpino Reto com Halteres",
                "Remada Baixa",
                "Afundo Alternado",
                "Desenvolvimento Ombro",
                "Prancha Abdominal",
                "Leg Press 45°",
                "Sulpino Reto Barra",
                "Crucifixo Máquina",
                "Rosca Direta",
                "Tríceps Corda",
                "Levantamento Terra",
                "Barra Fixa"
            };
            for (String nome : nomesExercicios) {
                Exercicios exercicio = new Exercicios();
                exercicio.setNomeExercicio(nome); // Usando o campo correto

                try {
                    GerenciadorIG.getMyInstance().getGerDom().inserirExercicios(exercicio);
                } catch (HibernateException ex) {
                    JOptionPane.showMessageDialog(this, ex, "Erro ao carregar os exercícios", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } else {
            for (Exercicios ex : listaExercicios) {
                switch (ex.getNomeExercicio()) {
                    case "Agachamento Livre" ->
                        checkBoxListaExercicios.put(ex, agachamento);
                    case "Sulpino Reto com Halteres" ->
                        checkBoxListaExercicios.put(ex, sulpinoHalter);
                    case "Remada Baixa" ->
                        checkBoxListaExercicios.put(ex, remadabaixa);
                    case "Afundo Alternado" ->
                        checkBoxListaExercicios.put(ex, afundo);
                    case "Desenvolvimento Ombro" ->
                        checkBoxListaExercicios.put(ex, desenvolvimento);
                    case "Prancha Abdominal" ->
                        checkBoxListaExercicios.put(ex, prancha);
                    case "Leg Press 45°" ->
                        checkBoxListaExercicios.put(ex, legPress);
                    case "Sulpino Reto Barra" ->
                        checkBoxListaExercicios.put(ex, sulpinoReto);
                    case "Crucifixo Máquina" ->
                        checkBoxListaExercicios.put(ex, crucifixo);
                    case "Rosca Direta" ->
                        checkBoxListaExercicios.put(ex, roscaDireta);
                    case "Tríceps Corda" ->
                        checkBoxListaExercicios.put(ex, tricepsCorda);
                    case "Levantamento Terra" ->
                        checkBoxListaExercicios.put(ex, terraLevantar);
                    case "Barra Fixa" ->
                        checkBoxListaExercicios.put(ex, barraFixa);
                }
            }
        }
    }//GEN-LAST:event_formComponentShown
 
    private void setarFicha(FichaAluno fichaDoAluno){
       exerciciosSelecionados = fichaDoAluno.getExercicios();
        
        for (Map.Entry<Exercicios, JCheckBox> entry : checkBoxListaExercicios.entrySet()) {
            Exercicios exercicio = entry.getKey();
            JCheckBox checkBox = entry.getValue();

            if (exerciciosSelecionados.contains(exercicio)) {
                checkBox.setSelected(true);
            } else {
                checkBox.setSelected(false);
            }
        }
        
        String tempoDescanso = String.valueOf(fichaDoAluno.getTempDescanso());
                
        spinnerMinRep.setValue(fichaDoAluno.getMinRep());
        comboDescanso.setSelectedItem(tempoDescanso);
        spinnerMaxRep.setValue(fichaDoAluno.getMaxRep());
        spinnerQTDserie.setValue(fichaDoAluno.getSerieExerc());
        textAreaObs.setText(fichaDoAluno.getObservacoes());
    }
    
    private void limparEscolhas() {
        
        nasciData.setDate(null);
        comboNomes.removeAllItems();
        txtGorduraCorp.setText("");
        txtPeso.setText("");
        for (Map.Entry<Exercicios, JCheckBox> entry : checkBoxListaExercicios.entrySet()) {
            JCheckBox checkBox = entry.getValue();
            checkBox.setSelected(false);
        }
        spinnerQTDserie.setValue(1);
        spinnerMaxRep.setValue(6);
        spinnerMinRep.setValue(4);
        comboDescanso.setSelectedItem("30");
        textAreaObs.setText("");
        txtIdade.setText("");
        txtAltura1.setText("");
    }  
    
    
    private boolean validarCampos(){
        String mensgErro = "";
        
        if(comboNomes.getSelectedItem() == null){
            mensgErro = mensgErro + "Escolha um nome válido\n";
            labelNome.setForeground(Color.red);
        }
        
        if(nasciData.getDate() == null){
            mensgErro = mensgErro + "Digite uma data de nascimento válido\n";
            labelNasci.setForeground(Color.red);
        }
        
        if(txtAltura1.getText().isEmpty()){
            mensgErro = mensgErro + "Digite uma altura válida\n";
            labelAltura.setForeground(Color.red);
        }
         
        if(txtPeso.getText().isEmpty()){
            mensgErro = mensgErro + "Digite um peso válido\n";
            labelPeso.setForeground(Color.red);
        }
 
        if(txtIdade.getText().isEmpty()){
            mensgErro = mensgErro + "Digite uma data válida\n";
            labelIdade.setForeground(Color.red);
        }
        
        if(exerciciosSelecionados.isEmpty()){
            mensgErro = mensgErro + "Escolha algum exercício\n";
        }
        
        if(txtGorduraCorp.getText().isEmpty()){
            mensgErro = mensgErro + "Digite uma porcentagem de gordura válida\n";
            labelGordura.setForeground(Color.red);
        }

        if(mensgErro.isEmpty()){
            setarCoresErro();
            return true;
        }else{
            JOptionPane.showMessageDialog(this, mensgErro, "Cadastro de aluno", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
    }

    private void setarCoresErro(){
        labelNome.setForeground(Color.black);
        labelAltura.setForeground(Color.black);
        labelGordura.setForeground(Color.black);
        labelIdade.setForeground(Color.black);
        labelNasci.setForeground(Color.black);
        labelNome.setForeground(Color.black);
        labelPeso.setForeground(Color.black);
    }
    
    public void setAlunoSelect(Aluno alunoSelect) {
        this.alunoSelect = alunoSelect;
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox afundo;
    private javax.swing.JCheckBox agachamento;
    private javax.swing.JCheckBox barraFixa;
    private javax.swing.JButton buttonBuscarAluno;
    private javax.swing.JComboBox<String> comboDescanso;
    private javax.swing.JComboBox<String> comboNomes;
    private javax.swing.JComboBox<String> comboTipoFicha;
    private javax.swing.JCheckBox crucifixo;
    private javax.swing.JCheckBox desenvolvimento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAltura;
    private javax.swing.JLabel labelGordura;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelNasci;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JCheckBox legPress;
    private com.toedter.calendar.JDateChooser nasciData;
    private javax.swing.JCheckBox prancha;
    private javax.swing.JCheckBox remadabaixa;
    private javax.swing.JCheckBox roscaDireta;
    private javax.swing.JSpinner spinnerMaxRep;
    private javax.swing.JSpinner spinnerMinRep;
    private javax.swing.JSpinner spinnerQTDserie;
    private javax.swing.JCheckBox sulpinoHalter;
    private javax.swing.JCheckBox sulpinoReto;
    private javax.swing.JCheckBox terraLevantar;
    private javax.swing.JTextArea textAreaObs;
    private javax.swing.JCheckBox tricepsCorda;
    private javax.swing.JTextField txtAltura1;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtGorduraCorp;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
