/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewer;

import DOMAIN.Aluno;
import GERENCIADOR.GerenciadorIG;
import GERENCIADOR.TableModelAniversario;
import GERENCIADOR.TableModelVencimento;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;


//Ao impletar o hibernate, a ideia é que ao iniciar o sistema ele coloque todos os aniversariantes do mês
//e as pessoas que estão chegando perto da validade de seu plano.

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private GerenciadorIG genIG;
    
    private TableModelVencimento tableVencimento;
    private TableModelAniversario tableAniversario;
    
    public TelaPrincipal(GerenciadorIG newGerenIG){
        genIG = newGerenIG;
        initComponents();
        this.setResizable(false);
        
        
        tableVencimento = new TableModelVencimento();
        tblVencimento.setModel(tableVencimento); 
        
        tableAniversario = new TableModelAniversario();
        tblAniversariantes.setModel(tableAniversario); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPopUp = new javax.swing.JPopupMenu();
        atualizar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVencimento = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAniversariantes = new javax.swing.JTable();
        labelFoto = new javax.swing.JLabel();
        MenuBarraPrinci = new javax.swing.JMenuBar();
        Cadastros = new javax.swing.JMenu();
        CadastroAluni = new javax.swing.JMenuItem();
        CadastroFicha = new javax.swing.JMenuItem();
        CadastroPersonal = new javax.swing.JMenuItem();
        menuPagamento = new javax.swing.JMenuItem();
        MenuBarPesqusiar = new javax.swing.JMenu();
        menuPersonal = new javax.swing.JMenuItem();
        menuFicha = new javax.swing.JMenuItem();
        menuAluno = new javax.swing.JMenuItem();

        atualizar.setText("Atualizar Tabelas");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        menuPopUp.add(atualizar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Vence em:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Aniversariantes:");

        tblVencimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Vencimento"
            }
        ));
        tblVencimento.setComponentPopupMenu(menuPopUp);
        jScrollPane3.setViewportView(tblVencimento);

        tblAniversariantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data do Aniversário"
            }
        ));
        tblAniversariantes.setComponentPopupMenu(menuPopUp);
        jScrollPane1.setViewportView(tblAniversariantes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 400, 390));

        labelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_Grande.jpg"))); // NOI18N
        getContentPane().add(labelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Cadastros.setText("Cadastro");
        Cadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrosActionPerformed(evt);
            }
        });

        CadastroAluni.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CadastroAluni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-cadastro-12.png"))); // NOI18N
        CadastroAluni.setText("Cadastro Aluno");
        CadastroAluni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAluniActionPerformed(evt);
            }
        });
        Cadastros.add(CadastroAluni);

        CadastroFicha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CadastroFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-novo-documento-12.png"))); // NOI18N
        CadastroFicha.setText("Cadastro Ficha");
        CadastroFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroFichaActionPerformed(evt);
            }
        });
        Cadastros.add(CadastroFicha);

        CadastroPersonal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CadastroPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-treinador-pessoal-12.png"))); // NOI18N
        CadastroPersonal.setText("Cadastro Personal");
        CadastroPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroPersonalActionPerformed(evt);
            }
        });
        Cadastros.add(CadastroPersonal);

        menuPagamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-pagamento-12.png"))); // NOI18N
        menuPagamento.setText("Cadastrar Pagamento");
        menuPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagamentoActionPerformed(evt);
            }
        });
        Cadastros.add(menuPagamento);

        MenuBarraPrinci.add(Cadastros);

        MenuBarPesqusiar.setText("Pesquisar");

        menuPersonal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-pesquisar-12.png"))); // NOI18N
        menuPersonal.setText("Pesquisar Personal");
        menuPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPersonalActionPerformed(evt);
            }
        });
        MenuBarPesqusiar.add(menuPersonal);

        menuFicha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-pesquisar-12.png"))); // NOI18N
        menuFicha.setText("Pesquisar Ficha");
        menuFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFichaActionPerformed(evt);
            }
        });
        MenuBarPesqusiar.add(menuFicha);

        menuAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-pesquisar-12.png"))); // NOI18N
        menuAluno.setText("Pesquisar Aluno");
        menuAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlunoActionPerformed(evt);
            }
        });
        MenuBarPesqusiar.add(menuAluno);

        MenuBarraPrinci.add(MenuBarPesqusiar);

        setJMenuBar(MenuBarraPrinci);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroAluniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAluniActionPerformed
        GerenciadorIG.getMyInstance().abrirTelaCadastroAluno();
    }//GEN-LAST:event_CadastroAluniActionPerformed

    private void CadastroFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroFichaActionPerformed
        GerenciadorIG.getMyInstance().abrirTelaCadastroFicha();
    }//GEN-LAST:event_CadastroFichaActionPerformed

    private void CadastroPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroPersonalActionPerformed
        GerenciadorIG.getMyInstance().abrirTelaCadastroPersonal();
    }//GEN-LAST:event_CadastroPersonalActionPerformed

    private void menuPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPersonalActionPerformed
        GerenciadorIG.getMyInstance().abrirTelaPesquisarPersonal();
    }//GEN-LAST:event_menuPersonalActionPerformed

    private void menuFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFichaActionPerformed
        GerenciadorIG.getMyInstance().abrirTelaPesquisarFicha();
    }//GEN-LAST:event_menuFichaActionPerformed

    private void menuAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlunoActionPerformed
        GerenciadorIG.getMyInstance().abrirTelaPesquisarAluno();
    }//GEN-LAST:event_menuAlunoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try{
            List<Aluno> listaAluno = GerenciadorIG.getMyInstance().getGerDom().listarAlunos(Aluno.class);
            
            if(listaAluno.size() > 0){
                tableAniversario.setLista(listaAluno);
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum registro encontrado.");
            }
            
        }catch (HibernateException ex){
            JOptionPane.showMessageDialog(this, "ERRO ao pesquisar aniversariantes! " + ex, "Tela Principal", JOptionPane.ERROR_MESSAGE);
        }
        
        try{
            List<Aluno> listaAluno = GerenciadorIG.getMyInstance().getGerDom().listarAlunos(Aluno.class);
            
            if(listaAluno.size() > 0){
                tableVencimento.setLista(listaAluno);
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum registro encontrado.");
            }
            
        }catch (HibernateException ex){
            JOptionPane.showMessageDialog(this, "ERRO ao pesquisar vencimentos! " + ex, "Tela Principal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formComponentShown

    private void menuPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagamentoActionPerformed
        GerenciadorIG.getMyInstance().abrirTelaPagamento();
    }//GEN-LAST:event_menuPagamentoActionPerformed

    private void CadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastrosActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        try{
            List<Aluno> listaAluno = GerenciadorIG.getMyInstance().getGerDom().listarAlunos(Aluno.class);
            
            if(listaAluno.size() > 0){
                tableAniversario.setLista(listaAluno);
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum registro encontrado.");
            }
            
        }catch (HibernateException ex){
            JOptionPane.showMessageDialog(this, "ERRO ao pesquisar aniversariantes! " + ex, "Tela Principal", JOptionPane.ERROR_MESSAGE);
        }
        
        try{
            List<Aluno> listaAluno = GerenciadorIG.getMyInstance().getGerDom().listarAlunos(Aluno.class);
            
            if(listaAluno.size() > 0){
                tableVencimento.setLista(listaAluno);
            }else{
                JOptionPane.showMessageDialog(this, "Nenhum registro encontrado.");
            }
            
        }catch (HibernateException ex){
            JOptionPane.showMessageDialog(this, "ERRO ao pesquisar vencimentos! " + ex, "Tela Principal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroAluni;
    private javax.swing.JMenuItem CadastroFicha;
    private javax.swing.JMenuItem CadastroPersonal;
    private javax.swing.JMenu Cadastros;
    private javax.swing.JMenu MenuBarPesqusiar;
    private javax.swing.JMenuBar MenuBarraPrinci;
    private javax.swing.JMenuItem atualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JMenuItem menuAluno;
    private javax.swing.JMenuItem menuFicha;
    private javax.swing.JMenuItem menuPagamento;
    private javax.swing.JMenuItem menuPersonal;
    private javax.swing.JPopupMenu menuPopUp;
    private javax.swing.JTable tblAniversariantes;
    private javax.swing.JTable tblVencimento;
    // End of variables declaration//GEN-END:variables
}
