/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhopoo2_alunos;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;

/**
 *
 * @author User
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastroAluno = new javax.swing.JMenuItem();
        CadastroProfessor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        CadastroAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CadastroAluno.setForeground(new java.awt.Color(0, 0, 0));
        CadastroAluno.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TrabalhoPOO2_Alunos\\src\\main\\resource\\Imagens\\icons8-adicionar-usuário-masculino-32.png")); // NOI18N
        CadastroAluno.setText("Cadastro Aluno");
        CadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroAluno);

        CadastroProfessor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CadastroProfessor.setForeground(new java.awt.Color(0, 0, 0));
        CadastroProfessor.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\TrabalhoPOO2_Alunos\\src\\main\\resource\\Imagens\\icons8-adicionar-usuário-masculino-32.png")); // NOI18N
        CadastroProfessor.setText("Cadastro Professor");
        CadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroProfessor);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void CadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAlunoActionPerformed
       CadastroAluno telaAluno = new CadastroAluno(this, true);
       telaAluno.setVisible(true);
    }//GEN-LAST:event_CadastroAlunoActionPerformed

    private void CadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
            Color darkBackground = new Color(30, 30, 30);
            Color darkForeground = new Color(200, 200, 200);
            Color darkButton = new Color(50, 50, 50);
            Color darkBorder = new Color(70, 70, 70);

            UIManager.put("Panel.background", darkBackground);
            UIManager.put("Button.background", darkButton);
            UIManager.put("Button.foreground", darkForeground);
            UIManager.put("Button.disabledText", new Color(100, 100, 100));
            UIManager.put("Button.border", BorderFactory.createLineBorder(darkBorder));

            UIManager.put("Label.foreground", darkForeground);
            UIManager.put("TextField.background", darkButton);
            UIManager.put("TextField.foreground", darkForeground);
            UIManager.put("TextField.caretForeground", Color.WHITE);
            UIManager.put("TextField.border", BorderFactory.createLineBorder(darkBorder));

            UIManager.put("TextArea.background", darkButton);
            UIManager.put("TextArea.foreground", darkForeground);
            UIManager.put("TextArea.border", BorderFactory.createLineBorder(darkBorder));

            UIManager.put("Menu.background", darkBackground);
            UIManager.put("Menu.foreground", darkForeground);
            UIManager.put("Menu.border", BorderFactory.createLineBorder(darkBorder));
            UIManager.put("Menu.disabledForeground", new Color(100, 100, 100));

            UIManager.put("MenuItem.background", darkButton);
            UIManager.put("MenuItem.foreground", darkForeground);
            UIManager.put("MenuItem.border", BorderFactory.createLineBorder(darkBorder));

            UIManager.put("List.background", darkBackground);
            UIManager.put("List.foreground", darkForeground);
            UIManager.put("List.selectionBackground", new Color(100, 100, 100));

            UIManager.put("Table.background", darkBackground);
            UIManager.put("Table.foreground", darkForeground);
            UIManager.put("Table.gridColor", darkBorder);
            
            UIManager.put("FormattedTextField.background", darkBackground);
            UIManager.put("FormattedTextField.foreground", darkForeground);
            UIManager.put("FormattedTextField.border", BorderFactory.createLineBorder(darkBorder));

            
            UIManager.put("RadioButton.background", darkButton);
            UIManager.put("RadioButton.foreground", darkForeground);
            UIManager.put("RadioButton.disabledText", new Color(100, 100, 100));
            UIManager.put("RadioButton.border", BorderFactory.createLineBorder(darkBorder));
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroAluno;
    private javax.swing.JMenuItem CadastroProfessor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
